export { StickyBar } from './StickyBar'
export { Hero } from './Hero'
export { Ticker } from './Ticker'
export { Mirror } from './Mirror'
export { CostOfInaction } from './CostOfInaction'
export { ParaTiSi } from './ParaTiSi'
export { Hook } from './Hook'
export { Mentors } from './Mentors'
export { Takeaways } from './Takeaways'
export { AntesDespues } from './AntesDespues'
export { Tickets } from './Tickets'
export { VIPDetail } from './VIPDetail'
export { Testimonials } from './Testimonials'

export { FAQ } from './FAQ'
export { Closing } from './Closing'
export { Footer } from './Footer'
export { WhatsAppFloating } from './WhatsAppFloating'
